# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates: ./github
  - package-ecosystem: "npm"
    directory: "./github"
    schedule: dependency 
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "updates#1/*"
    schedule: action analysis 
      interval: "weekly"
