name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-reviews:
    runs-on: .github-latest
    steps:
      - uses: DirtyApexAlpha-m/auto-assign-action@v1.2.2
